### ISSUE TITLE
how do I add vhost in apache?

### ISSUE THREAD

**Issue by shiroamada** [bylexus/docker-apache-php56#1]
how do I add vhost in apache? and keep the setting after I restart the docker?

**Comment by bylexus** [comment]
You have to modify the Apache config file:

You can do this using `docker copy`, fetching the config file from the container, modify it locally, then copy it back:

```
$ docker cp <yourcontainer>:/etc/apache2/sites-available/000-default.conf apache-config.conf
$ $EDITOR apache-config.conf
$ docker cp apache-config.conf <yourcontainer>:/etc/apache2/sites-available/000-default.conf
$ docker restart <yourcontainer>
```
